#  프로그램이 시작하면 제일 먼저 실행하는 파일이 application.yml 파일이다.


# localhost:8000/---- 이렇게 시작한다.
server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update  # 테이블을 처음 생성하는 경우에만 create로 만들고 아니면 update로 바꾸어야 한다.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #@Entity에서 선언한 변수의 이름 그대로 테이블을 만들겠다.
      use-new-id-generator-mappings: false # jpa의 기본 넘버링 전략을 따라가지 않겠다. 내가 auto_increment를 주겠다.
    show-sql: true # table이 create된 후 console에서 볼 수 있도록 보여주기
    properties:
      hibernate.format_sql: true # table이 create 된 후 console에서 보는 경우 자동으로 정렬됨

  jackson:
    serialization:
      fail-on-empty-beans: false